// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zagpzyzolwzhzxithgcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZ3B6eXpvbHd6aHp4aXRoZ2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTUyNTQsImV4cCI6MjA3MTYzMTI1NH0.DHNYqqsGw6RA-5qIzYffZD3ZaR29C7hkIxFzlJ6xVyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});